name: CI

on:
  push:
    branches: [PR]
  pull_request:
    branches: [main]
jobs:
  verify:
    name: Verify Files
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Install packages
      run: npm ci
    - name: tests
      run: npm test
    - name: Lint
      run: npx eslint ./src/Application.tsx